
# Offense count: 1
Lint/UselessAssignment:
  Exclude:
    - 'lib/redis/key_hash.rb'

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/redis/key_hash.rb'

# Offense count: 2
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/redis/key_hash.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/EmptyLiteral:
  Exclude:
    - 'lib/redis/key_hash.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  Exclude:
    - 'Rakefile'
    - 'lib/redis/key_hash.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Exclude:
    - 'lib/redis/key_hash.rb'

# Offense count: 1
# Configuration parameters: SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/MethodName:
  EnforcedStyle: snake_case

# Offense count: 10
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  MinDigits: 6
